// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/aws/aws-sdk-go-v2/service/sqs"
	"github.com/jhonromerou/magneto-brain/context/functions/analysis/v1/internal"
	"github.com/jhonromerou/magneto-brain/src/infrastructure/awscommon"
	"github.com/jhonromerou/magneto-brain/src/infrastructure/awssqs"
	"github.com/jhonromerou/magneto-brain/src/infrastructure/dotenv"
	"github.com/jhonromerou/magneto-brain/src/infrastructure/logruslogger"
	"github.com/jhonromerou/magneto-brain/src/repositories"
	"github.com/sirupsen/logrus"
)

// Injectors from wire.go:

func Initialize() (*internal.Handler, error) {
	logger := logruslogger.NewLogrusLoggerProvider()
	entry := logrus.NewEntry(logger)
	logrusLogger := logruslogger.NewLogrusLogger(entry)
	config, err := awscommon.ConfigProvider()
	if err != nil {
		return nil, err
	}
	v := awssqs.SqsOptions()
	client := sqs.NewFromConfig(config, v...)
	awsSqs := awssqs.NewAwsSqs(client)
	dotEnvEnvironmentReposity := dotenv.NewDotEnvEnvironmentReposity()
	awsSqsAnalysisRepository := repositories.NewQueueAnalysisRepository(awsSqs, dotEnvEnvironmentReposity)
	handler := internal.NewHandler(logrusLogger, awsSqsAnalysisRepository)
	return handler, nil
}
