// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// DatabaseInsertOne is an autogenerated mock type for the DatabaseInsertOne type
type DatabaseInsertOne struct {
	mock.Mock
}
