// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Logger is an autogenerated mock type for the Logger type
type Logger struct {
	mock.Mock
}

// Error provides a mock function with given fields: message
func (_m *Logger) Error(message string) {
	_m.Called(message)
}

// ErrorWithDetail provides a mock function with given fields: err, message
func (_m *Logger) ErrorWithDetail(err error, message string) {
	_m.Called(err, message)
}

// Info provides a mock function with given fields: message
func (_m *Logger) Info(message string) {
	_m.Called(message)
}
