// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// QueueRepository is an autogenerated mock type for the QueueRepository type
type QueueRepository struct {
	mock.Mock
}

// PublishMessage provides a mock function with given fields: message
func (_m *QueueRepository) PublishMessage(message string) error {
	ret := _m.Called(message)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(message)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetQueueName provides a mock function with given fields: queueName
func (_m *QueueRepository) SetQueueName(queueName string) {
	_m.Called(queueName)
}
