// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	domain "github.com/jhonromerou/magneto-brain/src/domain"
	mock "github.com/stretchr/testify/mock"
)

// StatsRepository is an autogenerated mock type for the StatsRepository type
type StatsRepository struct {
	mock.Mock
}

// GetDnaAnalysisByName provides a mock function with given fields: name
func (_m *StatsRepository) GetDnaAnalysisByName(name string) (domain.StatsModel, error) {
	ret := _m.Called(name)

	var r0 domain.StatsModel
	if rf, ok := ret.Get(0).(func(string) domain.StatsModel); ok {
		r0 = rf(name)
	} else {
		r0 = ret.Get(0).(domain.StatsModel)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewDnaAnalysisWithName provides a mock function with given fields: name
func (_m *StatsRepository) NewDnaAnalysisWithName(name string) error {
	ret := _m.Called(name)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetDnaAnalysis provides a mock function with given fields: item
func (_m *StatsRepository) SetDnaAnalysis(item domain.StatsModel) error {
	ret := _m.Called(item)

	var r0 error
	if rf, ok := ret.Get(0).(func(domain.StatsModel) error); ok {
		r0 = rf(item)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
